### ISSUE TITLE
Styling the header layout

### ISSUE THREAD

**Issue by juniorabranches** [juniorabranches/react-native-loginExample#12]
Home Screen > Click on button "Acessar":
Styling the header layout this way

![capturar](https://user-images.githubusercontent.com/9979222/31389821-323e666a-ada0-11e7-8d2b-bd3e3f1ef6a3.PNG)

**Comment by worachatsun** [comment]
#26

**Comment by juniorabranches** [comment]
Thanks!!! @worachatsun , cool
