### ISSUE TITLE
Open Image

### ISSUE THREAD

**Issue by juniorabranches** [juniorabranches/react-native-loginExample#13]
Home Screen > Click on button "Acessar":
When you click on an item in "Masonry" Component, open a corresponding image.

**Comment by abhishek71994** [comment]
Can you describe this a bit more? I would like to work on this.

**Comment by juniorabranches** [comment]
Sure... when clicking on a masonry image, on another screen will load the image, okay? thank you

**Comment by juniorabranches** [comment]
@abhishek71994 Are you still interested in this?

**Comment by abhishek71994** [comment]
Sorry, I'm working on some other project and wont be able to give any time.

**Comment by marinsokol** [comment]
Hi, can I work on this? Do you whan to open new screen or react native modal is good option

**Comment by juniorabranches** [comment]
@abhishek71994 Ah yes, ok friend, hugs.

**Comment by juniorabranches** [comment]
@marinsokol Hi, of course you can, feel free. If it opened a new screen would be perfect. thank you for that

**Comment by marinsokol** [comment]
Do you need header to go back?

**Comment by juniorabranches** [comment]
@marinsokol no .. intention is not to use header, just the button

**Comment by marinsokol** [comment]
I checked out new branch, but I can't  push it to repo. I will like to push my branch to make PR

**Comment by marinsokol** [comment]
I made PR #24

**Comment by juniorabranches** [comment]
@marinsokol thnak you so much!!!
