### ISSUE TITLE
Add Loading

### ISSUE THREAD

**Issue by juniorabranches** [juniorabranches/react-native-loginExample#14]
Add Loading on the label "Não tem uma conta? Cadastre-se agora" on the Home screen.

**Comment by esslamben** [comment]
Hey, I can look into this. Could you provide a better description of what you want ?

**Comment by juniorabranches** [comment]
Sure @Esslamb , 
When you go to the next screen, open loading ...
Something similar to this:
https://github.com/joinspontaneous/react-native-loading-spinner-overlay

**Comment by juniorabranches** [comment]
@Esslamb Are you still interested in this?

**Comment by worachatsun** [comment]
#25

**Comment by juniorabranches** [comment]
great!! thanks @worachatsun

**Comment by esslamben** [comment]
@juniorabranches Apologies for not replying. I had some work stuff going on so completely forgot about it. I'm glad somebody else picked it up 👍

**Comment by juniorabranches** [comment]
@Esslamb ok, thanks
