### ISSUE TITLE
Change DropDown 

### ISSUE THREAD

**Issue by juniorabranches** [juniorabranches/react-native-loginExample#17]
Home Screen > Click on label "Não tem uma conta? Cadastre-se agora":

I need to change the DropDown
![dwopdown](https://user-images.githubusercontent.com/9979222/31459213-82be3430-ae90-11e7-82df-b280653b4883.png)
![droow](https://user-images.githubusercontent.com/9979222/31459212-829e1d80-ae90-11e7-9fb8-94a088eba369.png)

by (for this)

![select](https://user-images.githubusercontent.com/9979222/31459229-8d7acd7a-ae90-11e7-8152-295481fead02.PNG)

**Comment by BrianCortes** [comment]
Hi , @juniorabranches I can help you with this issue 👍

**Comment by juniorabranches** [comment]
Cool @BrianCortes , thanks for this!!

**Comment by juniorabranches** [comment]
@BrianCortes Are you still interested in this?

**Comment by BrianCortes** [comment]
@juniorabranches yea, but I've been looking some library for do it,  for example this https://github.com/sohobloo/react-native-modal-dropdown so I tried custom styles, but in react native is very difficult , do you now other library for do it ?  or I've been thinking in making a select from 0

**Comment by juniorabranches** [comment]
Oh yes, That is OK. in fact it is at your discretion .. you decide
