### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by juniorabranches** [juniorabranches/react-native-loginExample#21]
Home Screen > Click on button "Access":
When searching for "Henry", bring only the image corresponding to the search.
That is, leave the functional search

**Comment by marinsokol** [comment]
I can do this

**Comment by juniorabranches** [comment]
@marinsokol sure, feel free, thanks

**Comment by marinsokol** [comment]
I have a little problem, I build search, but Masonry is not updating at all.

**Comment by juniorabranches** [comment]
@marinsokol It's true, I'll try to look for something about it ..
Thank you friend

**Comment by marinsokol** [comment]
Do you want PR of what i have done, so you can finish when you find solution?

**Comment by juniorabranches** [comment]
@marinsokol I think I already accepted the PR .. but I will leave it open yet .. thanks

**Comment by marinsokol** [comment]
I didn't make PR for this issue. I will make it later

**Comment by juniorabranches** [comment]
@marinsokol Nice, thank you.

**Comment by juniorabranches** [comment]
Thanks, I just accepted the PR ...
I'll test here, thank you !! @marinsokol
