### ISSUE TITLE
Check internet connection

### ISSUE THREAD

**Issue by juniorabranches** [juniorabranches/react-native-loginExample#22]
Check if there is a connection to an internet, if there is none, to alert the user that 
"there is no connection to an internet"

**Comment by arijitAD** [comment]
I am trying this.

**Comment by lokeshkvn** [comment]
Should I take this issue?

**Comment by juniorabranches** [comment]
@lokeshkvn sure, feel free!

**Comment by juniorabranches** [comment]
@lokeshkvn Are you still interested in this?

**Comment by lokeshkvn** [comment]
No progress till now , you can assign this to anyone else.

**Comment by juniorabranches** [comment]
@lokeshkvn ok.. All right, I'll leave it open, thank you.

**Comment by abiduzz420** [comment]
I shall take this up!

**Comment by juniorabranches** [comment]
@abiduzz420 great, thanks!

**Comment by felixaa** [comment]
If you're having trouble I can jump in on this

**Comment by juniorabranches** [comment]
@felixaa I would be very happy if you would help me ..

**Comment by felixaa** [comment]
I'll try to make a PR by tomorrow

**Comment by juniorabranches** [comment]
@felixaa great! Thanks
