### ISSUE TITLE
Validation (Red label)

### ISSUE THREAD

**Issue by juniorabranches** [juniorabranches/react-native-loginExample#30]
In Home Screen (Login), 
When entering the login and password fields incorrectly, change the alert by the red label below the field, something like the image below
![capturar](https://user-images.githubusercontent.com/9979222/31642651-60afd2d2-b2c2-11e7-805f-756b7c5541ad.PNG)

**Comment by felixaa** [comment]
I'll jump on this!

**Comment by juniorabranches** [comment]
@felixaa thanks!!
