### ISSUE TITLE
Back Button

### ISSUE THREAD

**Issue by juniorabranches** [juniorabranches/react-native-loginExample#34]
Home Screen > Click on "Logout Test":
Home Screen > Click on button "Access":

On the Logout and Feed screen, create back button.

**Comment by raheemazeezabiodun** [comment]
Hi,

can i do this?

**Comment by juniorabranches** [comment]
@raheemazeezabiodun hi.. Course man.. Thanks!

**Comment by raheemazeezabiodun** [comment]
Okay,

on it.

**Comment by juniorabranches** [comment]
@raheemazeezabiodun the man, are you going to get this issue? Thanks!

**Comment by raheemazeezabiodun** [comment]
Yeah, will push soon, i was doing some other stuff

**Comment by juniorabranches** [comment]
@raheemazeezabiodun great man.. Thanks

**Comment by raheemazeezabiodun** [comment]
where should the back button be directed to? Login component?

**Comment by juniorabranches** [comment]
yeah!!

**Comment by raheemazeezabiodun** [comment]
cool

**Comment by raheemazeezabiodun** [comment]
done, submitted a pr

**Comment by juniorabranches** [comment]
thanks man!
