### ISSUE TITLE
Select Items

### ISSUE THREAD

**Issue by juniorabranches** [juniorabranches/react-native-loginExample#35]
Home Screen> Click on label "Do not have an account? Register now":
In Select,
Add 3 test items to select component...
something like that:
![select](https://user-images.githubusercontent.com/9979222/31698427-f5622700-b393-11e7-998c-f2878b62b3f8.PNG)

**Comment by raheemazeezabiodun** [comment]
Hi,

should i take this up?

**Comment by juniorabranches** [comment]
@raheemazeezabiodun sure.. feel free!

**Comment by raheemazeezabiodun** [comment]
Okay,

I will push very soon

Thanks

**Comment by juniorabranches** [comment]
hi @raheemazeezabiodun 
thanks for the PR, but the select should be with this layout, and the items going down, understood?
I could not do it...
DropDown is not for me, thanks again
