### ISSUE TITLE
Validate Fields

### ISSUE THREAD

**Issue by juniorabranches** [juniorabranches/react-native-loginExample#36]
Home Screen > Click on label "Registre Now":
Validate the "username", "profession", "email", "password" and "password confirmation" fields in the "Register" button of the Registration screen

**Comment by AaronDills** [comment]
I'm on this one

**Comment by ajlatour** [comment]
What validation rules are you looking to implement for these inputs? Without more information, it's difficult to provide appropriate help.

**Comment by juniorabranches** [comment]
@ajlatour hi friend .. actually it will not be necessary anymore, I'll close this issue. but feel free to take another :smile:

**Comment by ajlatour** [comment]
Gotcha! All the best mate.
