### ISSUE TITLE
Validation Fields

### ISSUE THREAD

**Issue by juniorabranches** [juniorabranches/react-native-loginExample#4]
Validate the "username", "profession", "email", "password" and "password confirmation" fields in the "Register" button of the Registration screen

**Comment by JaredsCode** [comment]
@juniorabranches Do you have specific rules for validation?

**Comment by juniorabranches** [comment]
Hi .. 
No.. Really, all fields are necessary for confirm form..
Thanks for question

**Comment by JaredsCode** [comment]
Thanks for the quick response.  I should have been a little more clear in my question.  What I meant to ask was do you have any special requirements, other than being present, for any of those fields?  Minimum length/strength for password, or anything like that.

**Comment by juniorabranches** [comment]
ah I'm sorry, I should be more attentive .. for now the password must be at least 6 characters and the email should be in the correct pattern (test@hotmail.com)

**Comment by nontachaiwebdev** [comment]
Anyone do this ? If not I will slove this.

**Comment by juniorabranches** [comment]
@nontachaiwebdev  Nice work, thank you so much!!

**Comment by juniorabranches** [comment]
@nontachaiwebdev Are you still interested in this?

**Comment by nontachaiwebdev** [comment]
Sure sorry for late now am vacation at Samui. I will do this tomorrow. Sorry for my late

**Comment by juniorabranches** [comment]
@nontachaiwebdev Do not worry .. Thanks
 and good fun.
