### ISSUE TITLE
 Validation Field Password

### ISSUE THREAD

**Issue by juniorabranches** [juniorabranches/react-native-loginExample#5]
Validate the "email" field in the "Send" button on the "I forgot my password"

**Comment by azharakbar** [comment]
Ok ... i will work on it ... @juniorabranches

**Comment by juniorabranches** [comment]
@azharakbar , shure, thanks

**Comment by rsnickell** [comment]
Email validation is notorious for corner cases you may not commonly consider as valid. Please utilize the w3c recommended regex for validation:

> /^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/

https://www.w3.org/TR/2012/WD-html-markup-20120320/input.email.html

**Comment by juniorabranches** [comment]
very good.. thank you and feel free to help :)

**Comment by juniorabranches** [comment]
@azharakbar Are you still interested in this?

**Comment by azharakbar** [comment]
@juniorabranches Sorry ... I forgot to update my status ... I am not experienced with reactjs ... sorry again for interrupting

**Comment by juniorabranches** [comment]
@azharakbar All right, no problem, my friend. See you.
