### ISSUE TITLE
 Add Loading

### ISSUE THREAD

**Issue by juniorabranches** [juniorabranches/react-native-loginExample#6]
Add Loading on the "Access" button on the Home screen

**Comment by cacahds** [comment]
can i get this one?

**Comment by juniorabranches** [comment]
Of course, feel free to @cacahds

**Comment by juniorabranches** [comment]
@cacahds Are you still interested in this?

**Comment by cacahds** [comment]
made a pull request this morning, sorry for the delay in replying
