### ISSUE TITLE
 Back Button

### ISSUE THREAD

**Issue by juniorabranches** [juniorabranches/react-native-loginExample#8]
Home Screen > Click on "Teste Tela Logout":
Home Screen > Click on button "Acessar":

On the Logout and Feed screen, create back button.

**Comment by nontachaiwebdev** [comment]
Can i do this with ios emulator ?

**Comment by juniorabranches** [comment]
Of course, feel free to do this.

**Comment by juniorabranches** [comment]
@nontachaiwebdev Are you still interested in this?
